// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjpkHg2aBuDa99MQNr4Lk4Q7Kc2XfrhBc',
    appId: '1:37413575761:web:5c439f14384f8d49166c70',
    messagingSenderId: '37413575761',
    projectId: 'login-12228',
    authDomain: 'login-12228.firebaseapp.com',
    storageBucket: 'login-12228.appspot.com',
    measurementId: 'G-EJ7KGEXPLR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTfSIzY_8T3cTxsSQAlszMWKrfZbsUl2w',
    appId: '1:37413575761:android:2af37cbc93577a5f166c70',
    messagingSenderId: '37413575761',
    projectId: 'login-12228',
    storageBucket: 'login-12228.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7ZwYa6QuZmOYvp32px7nsBGLCowFSkF4',
    appId: '1:37413575761:ios:5d270732788cfab2166c70',
    messagingSenderId: '37413575761',
    projectId: 'login-12228',
    storageBucket: 'login-12228.appspot.com',
    iosBundleId: 'com.example.asistenciaupeuFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7ZwYa6QuZmOYvp32px7nsBGLCowFSkF4',
    appId: '1:37413575761:ios:bffdefb752da7ef1166c70',
    messagingSenderId: '37413575761',
    projectId: 'login-12228',
    storageBucket: 'login-12228.appspot.com',
    iosBundleId: 'com.example.asistenciaupeuFrontend.RunnerTests',
  );
}
